version: '3'
services:
  breeze-nginx:
    container_name: breeze-nginx
    image: breeze-nginx
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    ports:
      - "443:443"
      - "80:80"
      - "17521:17521"
    expose:
      - "443"
      - "80"
      - "17521"
    volumes:
      - ./dist:/usr/local/breeze/breeze-ui
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    networks:
      - breeze-net

networks:
  breeze-net:
    external: true
